---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure NTP-related packages are installed.
  package:
    name: ntp
    state: present
  environment: "{{ ntp_proxy_env }}"

- name: "Ensure {{ ntp_timezone_pkg }} package is installed (Linux)."
  package:
    name: "{{ ntp_timezone_pkg }}"
    state: present
  environment: "{{ ntp_proxy_env }}"
  when: ansible_system == "Linux"

- include: clock-rhel.yml
  when: ansible_os_family == 'RedHat'

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"

- name: "Ensure NTP is {{ 'started' if ntp_enabled else 'stopped' }}"
  service:
    name: "{{ ntp_daemon }}"
    state: "{{ 'started' if ntp_enabled else 'stopped' }}"
  when: ntp_manage_state

- name: "Ensure NTP is {{ 'enabled' if ntp_enabled else 'disabled' }}"
  service:
    name: "{{ ntp_daemon }}"
    enabled: "{{ 'yes' if ntp_enabled else 'no' }}"

- name: Generate ntp.conf file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp
  when: ntp_manage_config
